FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY tsconfig.json ./
COPY nest-cli.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

COPY apps/auth-service ./apps/auth-service
COPY libs ./libs

EXPOSE 3001

CMD ["npm", "run", "start:auth"]
