FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY tsconfig.json ./
COPY nest-cli.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

COPY apps/admin-service ./apps/admin-service
COPY libs ./libs

EXPOSE 3004

CMD ["npm", "run", "start:admin"]
