FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY tsconfig.json ./
COPY nest-cli.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

COPY apps/meal-service ./apps/meal-service
COPY libs ./libs

EXPOSE 3003

CMD ["npm", "run", "start:meal"]
